version: "3.9"

services:

  nodeapp:
    container_name: nodeapp-prod
    build:
      context: ./app
    ports:
      - "8080:8080" # http port
      - "9000:9000" # debug port
    networks:
      - app-network
    restart: on-failure
    # volumes:
    #  - ./app:/usr/src/app # need the same as WORKDIR and obrigatory run {npm install} localy! to map local to remoto

networks:
  app-network:
    driver: bridge
